# This file configures the static analysis results for your project (errors,
# warnings, and lints).
#
# This enables the 'recommended' set of lints from `package:lints`.
# This set helps identify many issues that may lead to problems when running
# or consuming Dart code, and enforces writing Dart using a single, idiomatic
# style and format.
#
# If you want a smaller set of lints you can change this to specify
# 'package:lints/core.yaml'. These are just the most critical lints
# (the recommended set includes the core lints).
# The core lints are also what is used by pub.dev for scoring packages.

include: package:flutter_lints/flutter.yaml

# Uncomment the following section to specify additional rules.

linter:
  rules:
    # Documentation
    - public_member_api_docs: true
    - package_api_docs: true
    - prefer_single_quotes: true
    - prefer_final_fields: true
    - prefer_const_constructors: true
    - prefer_const_declarations: true
    - avoid_print: true
    - avoid_empty_else: true
    - avoid_relative_lib_imports: true
    - avoid_types_as_parameter_names: true
    - avoid_unused_constructor_parameters: true
    - avoid_void_async: true
    - await_only_futures: true
    - camel_case_types: true
    - constant_identifier_names: true
    - empty_catches: true
    - empty_constructor_bodies: true
    - empty_statements: true
    - hash_and_equals: true
    - implementation_imports: true
    - library_names: true
    - library_prefixes: true
    - non_constant_identifier_names: true
    - prefer_typing_uninitialized_variables: true
    - sort_child_properties_last: true
    - sort_constructors_first: true
    - sort_unnamed_constructors_first: true
    - unnecessary_brace_in_string_interps: true
    - unnecessary_const: true
    - unnecessary_new: true
    - unnecessary_null_aware_assignments: true
    - unnecessary_null_in_if_null_operators: true
    - unnecessary_this: true
    - unrelated_type_equality_checks: true
    - use_full_hex_values_for_flutter_colors: true
    - use_rethrow_when_possible: true
    - use_setters_to_change_properties: true
    - use_string_buffers: true
    - valid_regexps: true

# analyzer:
#   exclude:
#     - path/to/excluded/files/**

# For more information about the core and recommended set of lints, see
# https://dart.dev/go/core-lints

# For additional information about configuring this file, see
# https://dart.dev/guides/language/analysis-options
