name: barcode_cleaner
description: A Flutter package for cleaning and formatting barcodes with various options including removing leading zeros, limiting length, and filtering characters.
version: 1.0.1
homepage: https://github.com/YousefMohamed6/barcode_cleaner
repository: https://github.com/YousefMohamed6/barcode_cleaner.git
issue_tracker: https://github.com/YousefMohamed6/barcode_cleaner/issues

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
